// Build the single Tailwind v4 stylesheet and wrap it as a TS module the
// Worker can inline into each page's <style>.
//
// Why a TS wrapper instead of importing the .css directly: the Worker returns
// HTML as strings, so it needs the CSS *as a string*. Emitting a committed
// `src/_generated-css.ts` means CI (typecheck/test/bundle) needs no Tailwind
// step — it just imports a normal module. Run `npm run build:css` whenever
// `src/styles.css` or any class name in src/ changes.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const input = join(root, "src", "styles.css");
const outTs = join(root, "src", "_generated-css.ts");

const tmp = mkdtempSync(join(tmpdir(), "mxga-css-"));
const outCss = join(tmp, "out.css");

try {
  // `@tailwindcss/cli` ships the `tailwindcss` binary. It auto-detects content
  // sources (scans the project for class names) and resolves @import/@theme.
  execFileSync("npx", ["--no-install", "tailwindcss", "-i", input, "-o", outCss, "--minify"], {
    cwd: root,
    stdio: "inherit",
  });

  const css = readFileSync(outCss, "utf8");
  // Escape for a JS template literal: backslash, backtick, and ${ interpolation.
  const escaped = css.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");

  const banner =
    "// AUTO-GENERATED by scripts/build-css.mjs — do not edit by hand.\n" +
    "// Source: src/styles.css. Regenerate with `npm run build:css`.\n";
  writeFileSync(outTs, `${banner}export const CSS = \`${escaped}\`;\n`);
  console.log(`build:css → ${outTs} (${(css.length / 1024).toFixed(1)} kb)`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
